import { MapPin, ChefHat, HeartHandshake, MessageCircle, Store, ArrowRight } from "lucide-react";

const categories = ["Пельмені та хінкалі", "Вареники", "Млинці", "Котлети та тефтелі", "Голубці та перці", "Картопляні вироби", "Сирники", "Пироги та піца"];
const reasons = [[ChefHat, "Відкрите виробництво", "Кухня та процес приготування — на видноті."], [HeartHandshake, "Домашні рецепти", "Зрозумілі страви для щоденних і святкових моментів."], [Store, "Широкий асортимент", "Меню формується для конкретного міста та магазину."]];

export const MenuSection = () => <section id="menu" className="section-padding bg-background"><div className="max-w-7xl mx-auto"><p className="text-primary text-sm font-bold tracking-[.25em] uppercase mb-4">Меню</p><h2 className="text-4xl md:text-6xl font-black">Оберіть свій <span className="text-primary">смак</span></h2><p className="mt-5 max-w-2xl text-muted-foreground text-lg">Асортимент, наявність та ціни залежать від міста. Спочатку оберіть найближчий магазин.</p><div className="mt-10 grid grid-cols-2 md:grid-cols-4 gap-3">{categories.map((name, i) => <a href="#shops" key={name} className="group min-h-32 rounded-2xl bg-muted p-5 flex flex-col justify-between hover:bg-primary hover:text-primary-foreground transition-colors"><span className="text-xs font-bold text-primary group-hover:text-white/80">0{i + 1}</span><span className="font-bold leading-tight">{name}</span><ArrowRight size={18}/></a>)}</div></div></section>;

export const WhySection = () => <section id="why" className="section-padding bg-stone-950 text-white"><div className="max-w-7xl mx-auto"><p className="text-red-300 text-sm font-bold tracking-[.25em] uppercase mb-4">Чому саме ми</p><h2 className="text-4xl md:text-6xl font-black max-w-3xl">Смак, який збирає рідних за одним столом</h2><div className="mt-12 grid md:grid-cols-3 gap-5">{reasons.map(([Icon, title, text]) => { const FeatureIcon = Icon as typeof ChefHat; return <article key={title as string} className="rounded-2xl border border-white/15 p-7"><FeatureIcon className="text-red-300"/><h3 className="mt-8 text-2xl font-bold">{title as string}</h3><p className="mt-3 text-white/65 leading-relaxed">{text as string}</p></article>; })}</div></div></section>;

export const ShopsSection = () => <section id="shops" className="section-padding bg-red-600 text-white"><div className="max-w-7xl mx-auto grid md:grid-cols-[1fr_auto] gap-10 items-end"><div><MapPin className="mb-5"/><p className="text-red-100 text-sm font-bold tracking-[.25em] uppercase mb-4">Наші магазини</p><h2 className="text-4xl md:text-6xl font-black">Знайдіть Галя Балувана у своєму місті</h2><p className="mt-5 max-w-xl text-red-100 text-lg">Вибір міста відкриває локальне меню, доступні способи отримання та контакти магазину.</p></div><button className="rounded-full bg-white px-7 py-4 font-bold text-red-700 hover:bg-red-50">Обрати місто</button></div></section>;

export const BlogSection = () => <section id="blog" className="section-padding"><div className="max-w-7xl mx-auto"><p className="text-primary text-sm font-bold tracking-[.25em] uppercase mb-4">Наш блог</p><h2 className="text-4xl md:text-6xl font-black">Корисне про домашній смак</h2><div className="mt-10 grid md:grid-cols-3 gap-5">{["Як швидко приготувати вечерю з напівфабрикатів", "Що обрати для сімейного столу", "Як зберігати заморожені домашні страви"].map((title, i) => <article key={title} className="rounded-2xl border border-border p-6"><span className="text-primary text-sm font-bold">0{i + 1}</span><h3 className="mt-10 text-2xl font-bold leading-tight">{title}</h3><button className="mt-8 inline-flex gap-2 items-center font-bold text-sm">Читати <ArrowRight size={16}/></button></article>)}</div></div></section>;

export const FeedbackSection = () => <section id="feedback" className="section-padding bg-muted"><div className="max-w-3xl mx-auto text-center"><MessageCircle className="mx-auto text-primary"/><h2 className="mt-5 text-4xl md:text-5xl font-black">Зворотний зв'язок</h2><p className="mt-4 text-muted-foreground text-lg">Залиште відгук або питання — менеджер вашого міста відповість у робочий час.</p><a href="mailto:hello@example.com" className="inline-flex mt-8 rounded-full bg-primary px-7 py-4 font-bold text-primary-foreground">Написати нам</a></div></section>;

export const FranchiseSection = () => <section id="franchise" className="section-padding bg-stone-950 text-white"><div className="max-w-7xl mx-auto grid md:grid-cols-[1.3fr_1fr] gap-10"><div><p className="text-red-300 text-sm font-bold tracking-[.25em] uppercase mb-4">Франшиза</p><h2 className="text-4xl md:text-6xl font-black">Хочете відкрити свій магазин?</h2></div><div><p className="text-white/65 leading-relaxed">Залиште контакти, щоб отримати актуальні умови та консультацію команди.</p><button className="mt-6 rounded-full border border-white/40 px-7 py-4 font-bold hover:bg-white hover:text-stone-950 transition-colors">Заявка на партнерство</button></div></div></section>;
